-- ============================================================
-- PharmaSys - Script d'installation complet pour Supabase
-- À exécuter dans Supabase > SQL Editor > New query > Run
-- ============================================================

-- 1. Table: tenants (espaces de travail)
CREATE TABLE IF NOT EXISTS tenants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nom text NOT NULL DEFAULT 'Mon Espace',
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenants_select_all" ON tenants FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "tenants_insert_all" ON tenants FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "tenants_update_all" ON tenants FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "tenants_delete_all" ON tenants FOR DELETE TO anon, authenticated USING (true);

-- 2. Table: inventaire (catalogue des médicaments)
CREATE TABLE IF NOT EXISTS inventaire (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom text NOT NULL DEFAULT '',
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    stock numeric DEFAULT 0,
    peremption date,
    categorie text NOT NULL DEFAULT 'Non classé',
    actif boolean DEFAULT true,
    dernier_controle timestamptz,
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE inventaire ENABLE ROW LEVEL SECURITY;

-- 3. Table: utilisateurs (comptes du personnel)
CREATE TABLE IF NOT EXISTS utilisateurs (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom text NOT NULL DEFAULT '',
    code text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT 'assistant',
    actif boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE utilisateurs ENABLE ROW LEVEL SECURITY;

-- 4. Table: tickets (tickets de vente)
CREATE TABLE IF NOT EXISTS tickets (
    id text PRIMARY KEY,
    date date NOT NULL,
    heure text DEFAULT '',
    assistant text DEFAULT '',
    assistant_id bigint,
    nb_articles integer DEFAULT 0,
    montant_total numeric DEFAULT 0,
    benefice_total numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    mode_paiement text DEFAULT 'ESPECES',
    client_id bigint,
    montant_paye numeric DEFAULT 0,
    montant_credit numeric DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;

-- 5. Table: ticket_lignes (lignes d'un ticket)
CREATE TABLE IF NOT EXISTS ticket_lignes (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticket_id text NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    produit_id bigint,
    nom text DEFAULT '',
    quantite numeric DEFAULT 0,
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    total numeric DEFAULT 0,
    profit numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE ticket_lignes ENABLE ROW LEVEL SECURITY;

-- 6. Table: historique_ventes (journal des ventes)
CREATE TABLE IF NOT EXISTS historique_ventes (
    id text PRIMARY KEY,
    date date NOT NULL,
    heure text DEFAULT '',
    assistant text DEFAULT '',
    assistant_id bigint,
    produit_id bigint,
    nom text DEFAULT '',
    quantite numeric DEFAULT 0,
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    total numeric DEFAULT 0,
    profit numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE historique_ventes ENABLE ROW LEVEL SECURITY;

-- 7. Table: mouvements_stock (journal des mouvements de stock)
CREATE TABLE IF NOT EXISTS mouvements_stock (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date text DEFAULT '',
    created_at timestamptz DEFAULT now(),
    assistant text DEFAULT '',
    produit_id bigint,
    produit text DEFAULT '',
    type text DEFAULT '',
    quantite numeric DEFAULT 0,
    stock_avant numeric DEFAULT 0,
    stock_apres numeric DEFAULT 0,
    observation text DEFAULT '',
    ticket text,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE mouvements_stock ENABLE ROW LEVEL SECURITY;

-- 8. Table: inventaires (cycles d'inventaire)
CREATE TABLE IF NOT EXISTS inventaires (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auteur text DEFAULT '',
    date_inventaire timestamptz DEFAULT now(),
    date_cloture timestamptz,
    statut text DEFAULT 'EN_COURS',
    nb_produits_actifs integer DEFAULT 0,
    nb_produits_controles integer DEFAULT 0,
    avancement numeric DEFAULT 0,
    nb_ecarts integer DEFAULT 0,
    pertes numeric DEFAULT 0,
    surplus numeric DEFAULT 0,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE inventaires ENABLE ROW LEVEL SECURITY;

-- 9. Table: controles_inventaire (contrôles individuels)
CREATE TABLE IF NOT EXISTS controles_inventaire (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inventaire_id bigint REFERENCES inventaires(id) ON DELETE CASCADE,
    produit_id bigint,
    produit_nom text DEFAULT '',
    stock_systeme numeric DEFAULT 0,
    stock_physique numeric DEFAULT 0,
    ecart numeric DEFAULT 0,
    valeur_ecart numeric DEFAULT 0,
    statut text DEFAULT 'A_ANALYSER',
    cause text,
    observation text,
    stock_corrige boolean DEFAULT false,
    auteur text DEFAULT '',
    date_controle timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE controles_inventaire ENABLE ROW LEVEL SECURITY;

-- 10. Table: parametres_pharmacie (infos pharmacie)
CREATE TABLE IF NOT EXISTS parametres_pharmacie (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom text DEFAULT 'Sekas pharma',
    adresse text DEFAULT '',
    telephone text DEFAULT '',
    email text DEFAULT '',
    rccm text DEFAULT '',
    slogan text DEFAULT '',
    logo_url text DEFAULT '',
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE parametres_pharmacie ENABLE ROW LEVEL SECURITY;

-- 11. Table: sessions (sessions utilisateurs)
CREATE TABLE IF NOT EXISTS sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id bigint NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'assistant',
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours')
);
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "session_select_all" ON sessions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "session_insert_all" ON sessions FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "session_update_all" ON sessions FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "session_delete_all" ON sessions FOR DELETE TO anon, authenticated USING (true);


-- 14. Finance V8 : clients, paiements et caisse
CREATE TABLE IF NOT EXISTS clients (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nom text NOT NULL, telephone text DEFAULT '', adresse text DEFAULT '',
  actif boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS paiements (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, ticket_id text REFERENCES tickets(id) ON DELETE SET NULL,
  client_id bigint REFERENCES clients(id) ON DELETE SET NULL, montant numeric NOT NULL, mode text NOT NULL,
  observation text DEFAULT '', assistant text DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE paiements ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS mouvements_caisse (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, type text NOT NULL, montant numeric NOT NULL,
  mode text NOT NULL DEFAULT 'ESPECES', motif text DEFAULT '', ticket_id text, client_id bigint REFERENCES clients(id) ON DELETE SET NULL,
  assistant text DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE mouvements_caisse ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 12. INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_inventaire_nom ON inventaire (nom);
CREATE INDEX IF NOT EXISTS idx_inventaire_actif ON inventaire (actif);
CREATE INDEX IF NOT EXISTS idx_inventaire_tenant ON inventaire(tenant_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_tenant ON utilisateurs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_date ON historique_ventes (date);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_produit ON historique_ventes (produit_id);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_assistant ON historique_ventes (assistant);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_tenant ON historique_ventes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tickets_date ON tickets (date);
CREATE INDEX IF NOT EXISTS idx_tickets_tenant ON tickets(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ticket_lignes_ticket ON ticket_lignes (ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_lignes_tenant ON ticket_lignes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mouvements_created ON mouvements_stock (created_at);
CREATE INDEX IF NOT EXISTS idx_mouvements_produit ON mouvements_stock (produit_id);
CREATE INDEX IF NOT EXISTS idx_mouvements_stock_tenant ON mouvements_stock(tenant_id);
CREATE INDEX IF NOT EXISTS idx_controles_inventaire ON controles_inventaire (inventaire_id);
CREATE INDEX IF NOT EXISTS idx_controles_inventaire_tenant ON controles_inventaire(tenant_id);
CREATE INDEX IF NOT EXISTS idx_inventaires_tenant ON inventaires(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parametres_pharmacie_tenant ON parametres_pharmacie(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sessions_tenant ON sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

-- ============================================================
-- 13. FONCTIONS DE SÉCURITÉ (SECURITY DEFINER)
-- ============================================================

-- Extraire le token de session de l'en-tête x-session-id
CREATE OR REPLACE FUNCTION current_session_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT NULLIF(current_setting('request.headers', true)::json->>'x-session-id', '')::uuid;
$$;

-- Résoudre le tenant_id depuis la session
CREATE OR REPLACE FUNCTION current_tenant_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT tenant_id FROM sessions
  WHERE id = current_session_id()
    AND expires_at > now();
$$;

-- Résoudre le rôle depuis la session
CREATE OR REPLACE FUNCTION current_user_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM sessions
  WHERE id = current_session_id()
    AND expires_at > now();
$$;

-- Résoudre le user_id depuis la session
CREATE OR REPLACE FUNCTION current_user_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT user_id FROM sessions
  WHERE id = current_session_id()
    AND expires_at > now();
$$;

-- Vérifier si la session actuelle est admin
CREATE OR REPLACE FUNCTION is_current_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE((
    SELECT role = 'admin' FROM sessions
    WHERE id = current_session_id()
      AND expires_at > now()
  ), false);
$$;

-- Créer une session
CREATE OR REPLACE FUNCTION create_session(p_user_id bigint, p_tenant_id uuid, p_role text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id uuid;
BEGIN
  INSERT INTO sessions (user_id, tenant_id, role)
  VALUES (p_user_id, p_tenant_id, p_role)
  RETURNING id INTO v_session_id;
  RETURN v_session_id;
END;
$$;

-- Valider une session
CREATE OR REPLACE FUNCTION validate_session(p_token uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session record;
  v_result json;
BEGIN
  SELECT s.id, s.user_id, s.tenant_id, s.role, s.expires_at,
         u.nom, u.code
  INTO v_session
  FROM sessions s
  JOIN utilisateurs u ON u.id = s.user_id AND u.tenant_id = s.tenant_id
  WHERE s.id = p_token
    AND s.expires_at > now()
    AND u.actif = true;

  IF v_session IS NULL THEN
    SELECT json_build_object('success', false, 'message', 'Session invalide ou expirée') INTO v_result;
  ELSE
    SELECT json_build_object(
      'success', true,
      'session', json_build_object(
        'id', v_session.id,
        'user_id', v_session.user_id,
        'tenant_id', v_session.tenant_id,
        'role', v_session.role,
        'nom', v_session.nom,
        'code', v_session.code
      )
    ) INTO v_result;
  END IF;

  RETURN v_result;
END;
$$;

-- Authentifier un utilisateur et créer une session
CREATE OR REPLACE FUNCTION authenticate_user(p_code text, p_tenant_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user record;
  v_session_id uuid;
  v_result json;
BEGIN
  SELECT id, nom, code, role, actif, tenant_id
  INTO v_user
  FROM utilisateurs
  WHERE code = p_code
    AND tenant_id = p_tenant_id
    AND actif = true;

  IF v_user IS NULL THEN
    SELECT json_build_object('success', false, 'message', 'Code incorrect ou compte désactivé') INTO v_result;
  ELSE
    PERFORM create_session(v_user.id, v_user.tenant_id, v_user.role);
    SELECT id INTO v_session_id FROM sessions
    WHERE user_id = v_user.id AND tenant_id = v_user.tenant_id
    ORDER BY created_at DESC LIMIT 1;

    SELECT json_build_object(
      'success', true,
      'user', json_build_object(
        'id', v_user.id,
        'nom', v_user.nom,
        'code', v_user.code,
        'role', v_user.role,
        'actif', v_user.actif,
        'tenant_id', v_user.tenant_id
      ),
      'session_token', v_session_id
    ) INTO v_result;
  END IF;

  RETURN v_result;
END;
$$;

-- Configurer un nouveau tenant + admin initial (pour l'onboarding)
CREATE OR REPLACE FUNCTION setup_tenant(p_tenant_name text DEFAULT 'Mon Espace', p_admin_code text DEFAULT 'admin')
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tenant_id uuid;
  v_admin_id bigint;
  v_result json;
BEGIN
  SELECT id INTO v_tenant_id FROM tenants WHERE nom = p_tenant_name LIMIT 1;
  IF v_tenant_id IS NULL THEN
    INSERT INTO tenants (nom) VALUES (p_tenant_name) RETURNING id INTO v_tenant_id;
  END IF;

  SELECT id INTO v_admin_id FROM utilisateurs WHERE tenant_id = v_tenant_id AND role = 'admin' LIMIT 1;
  IF v_admin_id IS NULL THEN
    v_admin_id := EXTRACT(EPOCH FROM now())::bigint;
    INSERT INTO utilisateurs (id, nom, code, role, actif, tenant_id)
    VALUES (v_admin_id, 'Administrateur', p_admin_code, 'admin', true, v_tenant_id);
  END IF;

  SELECT json_build_object(
    'success', true,
    'tenant_id', v_tenant_id,
    'tenant_name', p_tenant_name,
    'admin_id', v_admin_id,
    'admin_code', p_admin_code
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- ============================================================
-- 14. POLITIQUES RLS (sécurité par tenant + rôle)
-- ============================================================

-- inventaire
CREATE POLICY "inv_select" ON inventaire FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "inv_insert" ON inventaire FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "inv_update" ON inventaire FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "inv_delete" ON inventaire FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- utilisateurs
CREATE POLICY "usr_select" ON utilisateurs FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "usr_insert" ON utilisateurs FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "usr_update" ON utilisateurs FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "usr_delete" ON utilisateurs FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- tickets
CREATE POLICY "tkt_select" ON tickets FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tkt_insert" ON tickets FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tkt_update" ON tickets FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "tkt_delete" ON tickets FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- ticket_lignes
CREATE POLICY "tl_select" ON ticket_lignes FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tl_insert" ON ticket_lignes FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tl_update" ON ticket_lignes FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "tl_delete" ON ticket_lignes FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- historique_ventes
CREATE POLICY "hv_select" ON historique_ventes FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "hv_insert" ON historique_ventes FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "hv_update" ON historique_ventes FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "hv_delete" ON historique_ventes FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- mouvements_stock
CREATE POLICY "ms_select" ON mouvements_stock FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "ms_insert" ON mouvements_stock FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "ms_update" ON mouvements_stock FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "ms_delete" ON mouvements_stock FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- inventaires
CREATE POLICY "inv_cycle_select" ON inventaires FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "inv_cycle_insert" ON inventaires FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "inv_cycle_update" ON inventaires FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "inv_cycle_delete" ON inventaires FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- controles_inventaire
CREATE POLICY "ci_select" ON controles_inventaire FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "ci_insert" ON controles_inventaire FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "ci_update" ON controles_inventaire FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "ci_delete" ON controles_inventaire FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- parametres_pharmacie
CREATE POLICY "pp_select" ON parametres_pharmacie FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "pp_insert" ON parametres_pharmacie FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "pp_update" ON parametres_pharmacie FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "pp_delete" ON parametres_pharmacie FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- ============================================================
-- 15. PERMISSIONS
-- ============================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON FUNCTION authenticate_user(text, uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION validate_session(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION create_session(bigint, uuid, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_session_id() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_tenant_id() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_user_role() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_user_id() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION is_current_admin() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION setup_tenant(text, text) TO anon, authenticated;

-- ============================================================
-- FIN - La base est prête. Vous pouvez maintenant lier l'application.
-- ============================================================
