-- ============================================================
-- PharmaSys - Script d'installation complet pour Supabase
-- À exécuter dans Supabase > SQL Editor > New query > Run
-- ============================================================

-- 1. Table: tenants (espaces de travail)
CREATE TABLE IF NOT EXISTS tenants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nom text NOT NULL DEFAULT 'Mon Espace',
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenants_select_all" ON tenants FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "tenants_insert_all" ON tenants FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "tenants_update_all" ON tenants FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "tenants_delete_all" ON tenants FOR DELETE TO anon, authenticated USING (true);

-- 2. Table: inventaire (catalogue des médicaments)
CREATE TABLE IF NOT EXISTS inventaire (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom text NOT NULL DEFAULT '',
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    stock numeric DEFAULT 0,
    peremption date,
    categorie text NOT NULL DEFAULT 'Non classé',
    actif boolean DEFAULT true,
    dernier_controle timestamptz,
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE inventaire ENABLE ROW LEVEL SECURITY;

-- 3. Table: utilisateurs (comptes du personnel)
CREATE TABLE IF NOT EXISTS utilisateurs (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom text NOT NULL DEFAULT '',
    code text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT 'assistant',
    actif boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE utilisateurs ENABLE ROW LEVEL SECURITY;

-- 4. Table: tickets (tickets de vente)
CREATE TABLE IF NOT EXISTS tickets (
    id text PRIMARY KEY,
    date date NOT NULL,
    heure text DEFAULT '',
    assistant text DEFAULT '',
    assistant_id bigint,
    nb_articles integer DEFAULT 0,
    montant_total numeric DEFAULT 0,
    benefice_total numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    mode_paiement text DEFAULT 'ESPECES',
    client_id bigint,
    montant_paye numeric DEFAULT 0,
    montant_credit numeric DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;

-- 5. Table: ticket_lignes (lignes d'un ticket)
CREATE TABLE IF NOT EXISTS ticket_lignes (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticket_id text NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    produit_id bigint,
    nom text DEFAULT '',
    quantite numeric DEFAULT 0,
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    total numeric DEFAULT 0,
    profit numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE ticket_lignes ENABLE ROW LEVEL SECURITY;

-- 6. Table: historique_ventes (journal des ventes)
CREATE TABLE IF NOT EXISTS historique_ventes (
    id text PRIMARY KEY,
    date date NOT NULL,
    heure text DEFAULT '',
    assistant text DEFAULT '',
    assistant_id bigint,
    produit_id bigint,
    nom text DEFAULT '',
    quantite numeric DEFAULT 0,
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    total numeric DEFAULT 0,
    profit numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    created_at timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE historique_ventes ENABLE ROW LEVEL SECURITY;

-- 7. Table: mouvements_stock (journal des mouvements de stock)
CREATE TABLE IF NOT EXISTS mouvements_stock (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date text DEFAULT '',
    created_at timestamptz DEFAULT now(),
    assistant text DEFAULT '',
    produit_id bigint,
    produit text DEFAULT '',
    type text DEFAULT '',
    quantite numeric DEFAULT 0,
    stock_avant numeric DEFAULT 0,
    stock_apres numeric DEFAULT 0,
    observation text DEFAULT '',
    ticket text,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE mouvements_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE mouvements_stock ADD COLUMN IF NOT EXISTS assistant_id bigint;

-- 8. Table: inventaires (cycles d'inventaire)
CREATE TABLE IF NOT EXISTS inventaires (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auteur text DEFAULT '',
    date_inventaire timestamptz DEFAULT now(),
    date_cloture timestamptz,
    statut text DEFAULT 'EN_COURS',
    nb_produits_actifs integer DEFAULT 0,
    nb_produits_controles integer DEFAULT 0,
    avancement numeric DEFAULT 0,
    nb_ecarts integer DEFAULT 0,
    pertes numeric DEFAULT 0,
    surplus numeric DEFAULT 0,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE inventaires ENABLE ROW LEVEL SECURITY;

-- 9. Table: controles_inventaire (contrôles individuels)
CREATE TABLE IF NOT EXISTS controles_inventaire (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inventaire_id bigint REFERENCES inventaires(id) ON DELETE CASCADE,
    produit_id bigint,
    produit_nom text DEFAULT '',
    stock_systeme numeric DEFAULT 0,
    stock_physique numeric DEFAULT 0,
    ecart numeric DEFAULT 0,
    valeur_ecart numeric DEFAULT 0,
    statut text DEFAULT 'A_ANALYSER',
    cause text,
    observation text,
    stock_corrige boolean DEFAULT false,
    auteur text DEFAULT '',
    date_controle timestamptz DEFAULT now(),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE controles_inventaire ENABLE ROW LEVEL SECURITY;
ALTER TABLE controles_inventaire ADD COLUMN IF NOT EXISTS assistant_id bigint;
ALTER TABLE controles_inventaire ADD COLUMN IF NOT EXISTS vente_date date;
ALTER TABLE controles_inventaire ADD COLUMN IF NOT EXISTS quantite_vendue numeric DEFAULT 0;
ALTER TABLE controles_inventaire ADD COLUMN IF NOT EXISTS stock_attendu numeric DEFAULT 0;
ALTER TABLE controles_inventaire ADD COLUMN IF NOT EXISTS source text DEFAULT 'INVENTAIRE';

-- 10. Table: parametres_pharmacie (infos pharmacie)
CREATE TABLE IF NOT EXISTS parametres_pharmacie (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom text DEFAULT 'Sekas pharma',
    adresse text DEFAULT '',
    telephone text DEFAULT '',
    email text DEFAULT '',
    rccm text DEFAULT '',
    slogan text DEFAULT '',
    logo_url text DEFAULT '',
    seuil_stock_critique numeric NOT NULL DEFAULT 2 CHECK (seuil_stock_critique >= 0),
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE parametres_pharmacie ENABLE ROW LEVEL SECURITY;

-- 11. Table: sessions (sessions utilisateurs)
CREATE TABLE IF NOT EXISTS sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id bigint NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'assistant',
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours')
);
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "session_select_all" ON sessions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "session_insert_all" ON sessions FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "session_update_all" ON sessions FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "session_delete_all" ON sessions FOR DELETE TO anon, authenticated USING (true);


-- 14. Finance V8 : clients, paiements et caisse
CREATE TABLE IF NOT EXISTS clients (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nom text NOT NULL, telephone text DEFAULT '', adresse text DEFAULT '',
  actif boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS paiements (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, ticket_id text REFERENCES tickets(id) ON DELETE SET NULL,
  client_id bigint REFERENCES clients(id) ON DELETE SET NULL, montant numeric NOT NULL, mode text NOT NULL,
  observation text DEFAULT '', assistant text DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE paiements ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS mouvements_caisse (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, type text NOT NULL, montant numeric NOT NULL,
  mode text NOT NULL DEFAULT 'ESPECES', motif text DEFAULT '', ticket_id text, client_id bigint REFERENCES clients(id) ON DELETE SET NULL,
  assistant text DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);
ALTER TABLE mouvements_caisse ENABLE ROW LEVEL SECURITY;
ALTER TABLE mouvements_caisse ADD COLUMN IF NOT EXISTS assistant_id bigint;

-- ============================================================
-- 12. INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_inventaire_nom ON inventaire (nom);
CREATE INDEX IF NOT EXISTS idx_inventaire_actif ON inventaire (actif);
CREATE INDEX IF NOT EXISTS idx_inventaire_tenant ON inventaire(tenant_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_tenant ON utilisateurs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_date ON historique_ventes (date);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_produit ON historique_ventes (produit_id);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_assistant ON historique_ventes (assistant);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_tenant ON historique_ventes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tickets_date ON tickets (date);
CREATE INDEX IF NOT EXISTS idx_tickets_tenant ON tickets(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ticket_lignes_ticket ON ticket_lignes (ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_lignes_tenant ON ticket_lignes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mouvements_created ON mouvements_stock (created_at);
CREATE INDEX IF NOT EXISTS idx_mouvements_produit ON mouvements_stock (produit_id);
CREATE INDEX IF NOT EXISTS idx_mouvements_stock_tenant ON mouvements_stock(tenant_id);
CREATE INDEX IF NOT EXISTS idx_controles_inventaire ON controles_inventaire (inventaire_id);
CREATE INDEX IF NOT EXISTS idx_controles_inventaire_tenant ON controles_inventaire(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mouvements_stock_tenant_date ON mouvements_stock(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mouvements_stock_tenant_assistant ON mouvements_stock(tenant_id, assistant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mouvements_stock_tenant_type_date ON mouvements_stock(tenant_id, type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_controles_vente_tenant_date ON controles_inventaire(tenant_id, vente_date, assistant_id);
CREATE INDEX IF NOT EXISTS idx_inventaires_tenant ON inventaires(tenant_id);
CREATE INDEX IF NOT EXISTS idx_parametres_pharmacie_tenant ON parametres_pharmacie(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sessions_tenant ON sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

-- ============================================================
-- 13. FONCTIONS DE SÉCURITÉ (SECURITY DEFINER)
-- ============================================================

-- Extraire le token de session de l'en-tête x-session-id
CREATE OR REPLACE FUNCTION current_session_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT NULLIF(current_setting('request.headers', true)::json->>'x-session-id', '')::uuid;
$$;

-- Résoudre le tenant_id depuis la session
CREATE OR REPLACE FUNCTION current_tenant_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT tenant_id FROM sessions
  WHERE id = current_session_id()
    AND expires_at > now();
$$;

-- Résoudre le rôle depuis la session
CREATE OR REPLACE FUNCTION current_user_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM sessions
  WHERE id = current_session_id()
    AND expires_at > now();
$$;

-- Résoudre le user_id depuis la session
CREATE OR REPLACE FUNCTION current_user_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT user_id FROM sessions
  WHERE id = current_session_id()
    AND expires_at > now();
$$;

-- Vérifier si la session actuelle est admin
CREATE OR REPLACE FUNCTION is_current_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE((
    SELECT role = 'admin' FROM sessions
    WHERE id = current_session_id()
      AND expires_at > now()
  ), false);
$$;

-- Créer une session
CREATE OR REPLACE FUNCTION create_session(p_user_id bigint, p_tenant_id uuid, p_role text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id uuid;
BEGIN
  INSERT INTO sessions (user_id, tenant_id, role)
  VALUES (p_user_id, p_tenant_id, p_role)
  RETURNING id INTO v_session_id;
  RETURN v_session_id;
END;
$$;

-- Valider une session
CREATE OR REPLACE FUNCTION validate_session(p_token uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session record;
  v_result json;
BEGIN
  SELECT s.id, s.user_id, s.tenant_id, s.role, s.expires_at,
         u.nom, u.code
  INTO v_session
  FROM sessions s
  JOIN utilisateurs u ON u.id = s.user_id AND u.tenant_id = s.tenant_id
  WHERE s.id = p_token
    AND s.expires_at > now()
    AND u.actif = true;

  IF v_session IS NULL THEN
    SELECT json_build_object('success', false, 'message', 'Session invalide ou expirée') INTO v_result;
  ELSE
    SELECT json_build_object(
      'success', true,
      'session', json_build_object(
        'id', v_session.id,
        'user_id', v_session.user_id,
        'tenant_id', v_session.tenant_id,
        'role', v_session.role,
        'nom', v_session.nom,
        'code', v_session.code
      )
    ) INTO v_result;
  END IF;

  RETURN v_result;
END;
$$;

-- Authentifier un utilisateur et créer une session
CREATE OR REPLACE FUNCTION authenticate_user(p_code text, p_tenant_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user record;
  v_session_id uuid;
  v_result json;
BEGIN
  SELECT id, nom, code, role, actif, tenant_id
  INTO v_user
  FROM utilisateurs
  WHERE code = p_code
    AND tenant_id = p_tenant_id
    AND actif = true;

  IF v_user IS NULL THEN
    SELECT json_build_object('success', false, 'message', 'Code incorrect ou compte désactivé') INTO v_result;
  ELSE
    PERFORM create_session(v_user.id, v_user.tenant_id, v_user.role);
    SELECT id INTO v_session_id FROM sessions
    WHERE user_id = v_user.id AND tenant_id = v_user.tenant_id
    ORDER BY created_at DESC LIMIT 1;

    SELECT json_build_object(
      'success', true,
      'user', json_build_object(
        'id', v_user.id,
        'nom', v_user.nom,
        'code', v_user.code,
        'role', v_user.role,
        'actif', v_user.actif,
        'tenant_id', v_user.tenant_id
      ),
      'session_token', v_session_id
    ) INTO v_result;
  END IF;

  RETURN v_result;
END;
$$;

-- Configurer un nouveau tenant + admin initial (pour l'onboarding)
CREATE OR REPLACE FUNCTION setup_tenant(p_tenant_name text DEFAULT 'Mon Espace', p_admin_code text DEFAULT 'admin')
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tenant_id uuid;
  v_admin_id bigint;
  v_result json;
BEGIN
  SELECT id INTO v_tenant_id FROM tenants WHERE nom = p_tenant_name LIMIT 1;
  IF v_tenant_id IS NULL THEN
    INSERT INTO tenants (nom) VALUES (p_tenant_name) RETURNING id INTO v_tenant_id;
  END IF;

  SELECT id INTO v_admin_id FROM utilisateurs WHERE tenant_id = v_tenant_id AND role = 'admin' LIMIT 1;
  IF v_admin_id IS NULL THEN
    v_admin_id := EXTRACT(EPOCH FROM now())::bigint;
    INSERT INTO utilisateurs (id, nom, code, role, actif, tenant_id)
    VALUES (v_admin_id, 'Administrateur', p_admin_code, 'admin', true, v_tenant_id);
  END IF;

  SELECT json_build_object(
    'success', true,
    'tenant_id', v_tenant_id,
    'tenant_name', p_tenant_name,
    'admin_id', v_admin_id,
    'admin_code', p_admin_code
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- ============================================================
-- 14. POLITIQUES RLS (sécurité par tenant + rôle)
-- ============================================================

-- inventaire
CREATE POLICY "inv_select" ON inventaire FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "inv_insert" ON inventaire FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "inv_update" ON inventaire FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "inv_delete" ON inventaire FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- utilisateurs
CREATE POLICY "usr_select" ON utilisateurs FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "usr_insert" ON utilisateurs FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "usr_update" ON utilisateurs FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "usr_delete" ON utilisateurs FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- tickets
CREATE POLICY "tkt_select" ON tickets FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tkt_insert" ON tickets FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tkt_update" ON tickets FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "tkt_delete" ON tickets FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- ticket_lignes
CREATE POLICY "tl_select" ON ticket_lignes FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tl_insert" ON ticket_lignes FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tl_update" ON ticket_lignes FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "tl_delete" ON ticket_lignes FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- historique_ventes
CREATE POLICY "hv_select" ON historique_ventes FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "hv_insert" ON historique_ventes FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "hv_update" ON historique_ventes FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "hv_delete" ON historique_ventes FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- mouvements_stock
CREATE POLICY "ms_select" ON mouvements_stock FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "ms_insert" ON mouvements_stock FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "ms_update" ON mouvements_stock FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "ms_delete" ON mouvements_stock FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- inventaires
CREATE POLICY "inv_cycle_select" ON inventaires FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "inv_cycle_insert" ON inventaires FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "inv_cycle_update" ON inventaires FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "inv_cycle_delete" ON inventaires FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- controles_inventaire
CREATE POLICY "ci_select" ON controles_inventaire FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "ci_insert" ON controles_inventaire FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "ci_update" ON controles_inventaire FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "ci_delete" ON controles_inventaire FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- parametres_pharmacie
CREATE POLICY "pp_select" ON parametres_pharmacie FOR SELECT TO anon, authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "pp_insert" ON parametres_pharmacie FOR INSERT TO anon, authenticated WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "pp_update" ON parametres_pharmacie FOR UPDATE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin()) WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());
CREATE POLICY "pp_delete" ON parametres_pharmacie FOR DELETE TO anon, authenticated USING (tenant_id = current_tenant_id() AND is_current_admin());

-- ============================================================
-- 15. PERMISSIONS
-- ============================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON FUNCTION authenticate_user(text, uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION validate_session(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION create_session(bigint, uuid, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_session_id() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_tenant_id() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_user_role() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION current_user_id() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION is_current_admin() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION setup_tenant(text, text) TO anon, authenticated;

-- ============================================================
-- FIN - La base est prête. Vous pouvez maintenant lier l'application.
-- ============================================================

-- 20260908000900 : seuils de stock par catégorie
CREATE TABLE IF NOT EXISTS seuils_stock_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  categorie text NOT NULL,
  seuil numeric NOT NULL DEFAULT 0 CHECK (seuil >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, categorie)
);
ALTER TABLE seuils_stock_categories ENABLE ROW LEVEL SECURITY;
-- PharmaSys: dépenses assistants + suivi consolidé des crédits
-- Les assistants passent par des RPC SECURITY DEFINER qui récupèrent leur
-- identité depuis la session serveur. Ils ne peuvent pas déclarer une dépense
-- au nom d'un autre utilisateur.

ALTER TABLE public.mouvements_caisse
  ADD COLUMN IF NOT EXISTS assistant_id bigint;

CREATE INDEX IF NOT EXISTS idx_mouvements_caisse_tenant_assistant_date
  ON public.mouvements_caisse(tenant_id, assistant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mouvements_caisse_tenant_depense_date
  ON public.mouvements_caisse(tenant_id, nature, created_at DESC)
  WHERE nature='DEPENSE';

-- Fonction dédiée aux dépenses saisies par l'assistant.
CREATE OR REPLACE FUNCTION public.enregistrer_depense_assistant(
  p_montant numeric,
  p_mode text DEFAULT 'ESPECES',
  p_motif text DEFAULT '',
  p_observation text DEFAULT ''
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_tenant_id uuid := current_tenant_id();
  v_user_id bigint := current_user_id();
  v_role text := current_user_role();
  v_nom text;
  v_id bigint;
  v_mode text := COALESCE(NULLIF(p_mode,''),'ESPECES');
  v_motif text := COALESCE(NULLIF(trim(p_motif),''),'Dépense assistant');
BEGIN
  IF v_tenant_id IS NULL OR v_user_id IS NULL THEN
    RAISE EXCEPTION 'Session invalide ou expirée';
  END IF;

  IF v_role NOT IN ('assistant','admin','Administrateur') THEN
    RAISE EXCEPTION 'Rôle non autorisé à enregistrer une dépense';
  END IF;

  IF p_montant IS NULL OR p_montant <= 0 THEN
    RAISE EXCEPTION 'Montant de dépense invalide';
  END IF;

  IF v_mode NOT IN ('ESPECES','MOBILE_MONEY','CARTE') THEN
    RAISE EXCEPTION 'Mode de paiement de dépense invalide';
  END IF;

  SELECT nom INTO v_nom
  FROM public.utilisateurs
  WHERE id=v_user_id AND tenant_id=v_tenant_id AND actif=true;

  IF v_nom IS NULL THEN
    RAISE EXCEPTION 'Utilisateur actif introuvable';
  END IF;

  INSERT INTO public.mouvements_caisse(
    type,montant,mode,motif,assistant,assistant_id,tenant_id,
    nature,reference_id,observation
  ) VALUES (
    'SORTIE',p_montant,v_mode,v_motif,v_nom,v_user_id,v_tenant_id,
    'DEPENSE',NULL,COALESCE(p_observation,'')
  ) RETURNING id INTO v_id;

  UPDATE public.mouvements_caisse
  SET reference_id='DEP-'||v_id::text
  WHERE id=v_id;

  RETURN jsonb_build_object(
    'success',true,
    'id',v_id,
    'assistant_id',v_user_id,
    'assistant',v_nom,
    'montant',p_montant,
    'nature','DEPENSE'
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.enregistrer_depense_assistant(numeric,text,text,text) TO anon, authenticated;

-- Solde réel des crédits, indépendant de la période sélectionnée dans le dashboard.
-- Une vente à crédit augmente la dette; un règlement de crédit la diminue.
CREATE OR REPLACE FUNCTION public.get_credit_balances()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_tenant_id uuid := current_tenant_id();
  v_result jsonb;
BEGIN
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'Session invalide ou expirée';
  END IF;

  SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.solde DESC),'[]'::jsonb)
  INTO v_result
  FROM (
    SELECT
      c.id AS client_id,
      c.nom AS client_nom,
      c.telephone,
      GREATEST(
        0,
        COALESCE((
          SELECT SUM(t.montant_credit)
          FROM public.tickets t
          WHERE t.tenant_id=v_tenant_id
            AND t.client_id=c.id
            AND t.statut='VALIDE'
            AND t.montant_credit>0
        ),0)
        -
        COALESCE((
          SELECT SUM(p.montant)
          FROM public.paiements p
          WHERE p.tenant_id=v_tenant_id
            AND p.client_id=c.id
            AND p.nature='REGLEMENT_CREDIT'
            AND p.montant>0
        ),0)
      ) AS solde
    FROM public.clients c
    WHERE c.tenant_id=v_tenant_id
      AND c.actif=true
  ) x
  WHERE x.solde>0;

  RETURN v_result;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_credit_balances() TO anon, authenticated;

-- Étendre le moteur hors-ligne à la déclaration de dépense.
CREATE OR REPLACE FUNCTION public.executer_operation_offline(
  p_operation_id text,
  p_operation_type text,
  p_payload jsonb
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  t uuid:=current_tenant_id();
  r jsonb;
BEGIN
  IF t IS NULL THEN RAISE EXCEPTION 'Session invalide ou expirée'; END IF;

  IF EXISTS(SELECT 1 FROM operations_sync WHERE operation_id=p_operation_id AND tenant_id=t) THEN
    SELECT result INTO r FROM operations_sync WHERE operation_id=p_operation_id AND tenant_id=t;
    RETURN COALESCE(r,jsonb_build_object('success',true,'already_processed',true));
  END IF;

  IF p_operation_id IS NULL OR length(trim(p_operation_id))<8 THEN
    RAISE EXCEPTION 'Identifiant d''opération invalide';
  END IF;

  CASE p_operation_type
    WHEN 'VENTE' THEN
      r:=valider_vente(
        p_payload->'ticket'->>'id',
        (p_payload->'ticket'->>'date')::date,
        COALESCE(p_payload->'ticket'->>'heure',''),
        COALESCE(p_payload->'ticket'->>'assistant','Système'),
        NULLIF(p_payload->'ticket'->>'assistant_id','')::bigint,
        COALESCE(p_payload->'lignes','[]'::jsonb),
        COALESCE(p_payload->'ticket'->'paiements',p_payload->'paiements','[]'::jsonb)
      );
    WHEN 'REAPPRO' THEN
      r:=reapprovisionner_stock((p_payload->>'p_produit_id')::bigint,(p_payload->>'p_quantite')::numeric,COALESCE(p_payload->>'p_observation','Reapprovisionnement'),COALESCE(p_payload->>'p_assistant','Système'));
    WHEN 'CONTROLE' THEN
      r:=enregistrer_controle_tournant((p_payload->>'p_produit_id')::bigint,(p_payload->>'p_stock_physique')::numeric,p_payload->>'p_cause',COALESCE(p_payload->>'p_observation','Contrôle tournant'),COALESCE(p_payload->>'p_auteur','Système'));
    WHEN 'ANALYSE_CONTROLE' THEN
      r:=traiter_controle_tournant((p_payload->>'p_controle_id')::bigint,p_payload->>'p_cause',COALESCE(p_payload->>'p_observation',''),COALESCE(p_payload->>'p_statut','A_SUIVRE'),COALESCE((p_payload->>'p_corriger_stock')::boolean,false));
    WHEN 'CAISSE' THEN
      r:=enregistrer_mouvement_caisse(p_payload->>'p_type',(p_payload->>'p_montant')::numeric,p_payload->>'p_mode',p_payload->>'p_motif',p_payload->>'p_assistant');
    WHEN 'DEPENSE_ASSISTANT' THEN
      r:=enregistrer_depense_assistant((p_payload->>'p_montant')::numeric,COALESCE(p_payload->>'p_mode','ESPECES'),COALESCE(p_payload->>'p_motif','Dépense assistant'),COALESCE(p_payload->>'p_observation',''));
    WHEN 'PAIEMENT_CREDIT' THEN
      r:=enregistrer_paiement_credit((p_payload->>'p_client_id')::bigint,(p_payload->>'p_montant')::numeric,p_payload->>'p_mode',p_payload->>'p_observation',p_payload->>'p_assistant');
    WHEN 'ANNULER_LIGNE_HISTORIQUE' THEN
      r:=annuler_ligne_ticket(p_payload->>'p_historique_id');
    WHEN 'ANNULER_ARTICLE' THEN
      r:=annuler_article_ticket((p_payload->>'p_ligne_id')::bigint);
    WHEN 'ANNULER_TICKET' THEN
      r:=annuler_ticket(p_payload->>'p_ticket_id');
    ELSE
      RAISE EXCEPTION 'Type d''opération hors-ligne inconnu : %',p_operation_type;
  END CASE;

  INSERT INTO operations_sync(operation_id,tenant_id,operation_type,payload,result)
  VALUES(p_operation_id,t,p_operation_type,p_payload,r);
  RETURN r;
END;
$$;
GRANT EXECUTE ON FUNCTION public.executer_operation_offline(text,text,jsonb) TO anon, authenticated;

-- ============================================================
-- Extensions assistants : dépenses, crédits consolidés et sécurité
-- ============================================================
ALTER TABLE public.mouvements_caisse ADD COLUMN IF NOT EXISTS assistant_id bigint;
CREATE INDEX IF NOT EXISTS idx_mouvements_caisse_tenant_assistant_date ON public.mouvements_caisse(tenant_id, assistant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mouvements_caisse_tenant_depense_date ON public.mouvements_caisse(tenant_id, nature, created_at DESC) WHERE nature='DEPENSE';

-- Les définitions RPC/policies de la migration 20261004000100 sont également
-- présentes dans le dépôt des migrations et doivent être appliquées après le
-- schéma de base pour les installations existantes.

-- ============================================================
-- PharmaSys V13.6.3 - Traçabilité stricte des crédits et règlements
-- ============================================================
-- ============================================================
-- PharmaSys - Traçabilité stricte des crédits et règlements
-- Un règlement est encaissé aujourd'hui mais reste rattaché à la
-- vente/crédit d'origine et donc à l'assistant vendeur d'origine.
-- ============================================================

ALTER TABLE public.paiements
  ADD COLUMN IF NOT EXISTS encaisseur_id bigint,
  ADD COLUMN IF NOT EXISTS encaisseur text;

CREATE INDEX IF NOT EXISTS idx_paiements_credit_client_date
  ON public.paiements(tenant_id, client_id, nature, created_at DESC);

CREATE TABLE IF NOT EXISTS public.reglements_credit_lignes (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  paiement_id bigint NOT NULL REFERENCES public.paiements(id) ON DELETE CASCADE,
  ticket_id text NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  montant numeric NOT NULL CHECK (montant > 0),
  assistant_id bigint,
  assistant text DEFAULT '',
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(paiement_id, ticket_id)
);
ALTER TABLE public.reglements_credit_lignes ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_reglements_credit_ticket
  ON public.reglements_credit_lignes(tenant_id, ticket_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reglements_credit_paiement
  ON public.reglements_credit_lignes(tenant_id, paiement_id);
CREATE INDEX IF NOT EXISTS idx_reglements_credit_assistant
  ON public.reglements_credit_lignes(tenant_id, assistant_id, created_at DESC);

DROP POLICY IF EXISTS reglements_credit_select ON public.reglements_credit_lignes;
CREATE POLICY reglements_credit_select ON public.reglements_credit_lignes
  FOR SELECT TO anon, authenticated
  USING (tenant_id=current_tenant_id() AND is_current_admin());

DROP POLICY IF EXISTS reglements_credit_insert ON public.reglements_credit_lignes;
CREATE POLICY reglements_credit_insert ON public.reglements_credit_lignes
  FOR INSERT TO anon, authenticated
  WITH CHECK (tenant_id=current_tenant_id() AND is_current_admin());

-- Compatibilité : les anciens règlements sans allocation sont répartis
-- chronologiquement sur les anciennes ventes à crédit du même client.
DO $$
DECLARE
  p record;
  t record;
  v_restant numeric;
  v_alloc numeric;
BEGIN
  FOR p IN
    SELECT pay.id,pay.client_id,pay.montant,pay.tenant_id,pay.created_at
    FROM public.paiements pay
    WHERE pay.nature='REGLEMENT_CREDIT'
      AND pay.client_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.reglements_credit_lignes r WHERE r.paiement_id=pay.id)
    ORDER BY pay.created_at,pay.id
  LOOP
    v_restant:=p.montant;
    FOR t IN
      SELECT tk.id,tk.montant_credit,tk.assistant_id,tk.assistant
      FROM public.tickets tk
      WHERE tk.tenant_id=p.tenant_id
        AND tk.client_id=p.client_id
        AND tk.statut='VALIDE'
        AND tk.montant_credit>0
      ORDER BY tk.date,tk.created_at,tk.id
      FOR UPDATE
    LOOP
      EXIT WHEN v_restant<=0;
      SELECT GREATEST(0,t.montant_credit-COALESCE(SUM(r.montant),0))
      INTO v_alloc
      FROM public.reglements_credit_lignes r
      WHERE r.tenant_id=p.tenant_id AND r.ticket_id=t.id;
      IF v_alloc>0 THEN
        v_alloc:=LEAST(v_alloc,v_restant);
        INSERT INTO public.reglements_credit_lignes(
          paiement_id,ticket_id,montant,assistant_id,assistant,tenant_id
        ) VALUES (
          p.id,t.id,v_alloc,t.assistant_id,t.assistant,p.tenant_id
        ) ON CONFLICT (paiement_id,ticket_id) DO NOTHING;
        v_restant:=v_restant-v_alloc;
      END IF;
    END LOOP;
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.enregistrer_paiement_credit(
  p_client_id bigint,
  p_montant numeric,
  p_mode text DEFAULT 'ESPECES',
  p_observation text DEFAULT '',
  p_assistant text DEFAULT ''
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_tenant uuid:=current_tenant_id();
  v_user_id bigint:=current_user_id();
  v_role text:=current_user_role();
  v_encaisseur text;
  v_paiement_id bigint;
  v_restant numeric:=p_montant;
  v_total_du numeric:=0;
  v_ticket record;
  v_du_ticket numeric;
  v_alloc numeric;
  v_allocations jsonb:='[]'::jsonb;
BEGIN
  IF v_tenant IS NULL OR v_user_id IS NULL THEN RAISE EXCEPTION 'Session invalide'; END IF;
  IF v_role NOT IN ('assistant','admin','Administrateur','caissier','pharmacien','responsable') THEN
    RAISE EXCEPTION 'Rôle non autorisé à encaisser un crédit';
  END IF;
  IF p_montant IS NULL OR p_montant<=0 THEN RAISE EXCEPTION 'Montant invalide'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.clients WHERE id=p_client_id AND tenant_id=v_tenant AND actif=true) THEN
    RAISE EXCEPTION 'Client invalide';
  END IF;

  SELECT nom INTO v_encaisseur
  FROM public.utilisateurs
  WHERE id=v_user_id AND tenant_id=v_tenant AND actif=true;
  IF v_encaisseur IS NULL THEN RAISE EXCEPTION 'Utilisateur actif introuvable'; END IF;

  -- Verrouille les ventes à crédit du client pour empêcher deux encaissements
  -- simultanés de consommer le même solde.
  FOR v_ticket IN
    SELECT tk.id,tk.montant_credit,tk.assistant_id,tk.assistant,tk.date,tk.created_at
    FROM public.tickets tk
    WHERE tk.tenant_id=v_tenant
      AND tk.client_id=p_client_id
      AND tk.statut='VALIDE'
      AND tk.montant_credit>0
    ORDER BY tk.date,tk.created_at,tk.id
    FOR UPDATE
  LOOP
    SELECT GREATEST(0,v_ticket.montant_credit-COALESCE(SUM(r.montant),0))
    INTO v_du_ticket
    FROM public.reglements_credit_lignes r
    WHERE r.tenant_id=v_tenant AND r.ticket_id=v_ticket.id;
    v_total_du:=v_total_du+COALESCE(v_du_ticket,0);
  END LOOP;

  IF p_montant>v_total_du+0.01 THEN
    RAISE EXCEPTION 'Le règlement (%) dépasse la dette restante du client (%)',p_montant,v_total_du;
  END IF;

  INSERT INTO public.paiements(
    ticket_id,client_id,montant,mode,observation,assistant,encaisseur_id,encaisseur,tenant_id,nature
  ) VALUES (
    NULL,p_client_id,p_montant,COALESCE(NULLIF(p_mode,''),'ESPECES'),
    COALESCE(p_observation,'Règlement crédit'),v_encaisseur,v_user_id,v_encaisseur,v_tenant,'REGLEMENT_CREDIT'
  ) RETURNING id INTO v_paiement_id;

  FOR v_ticket IN
    SELECT tk.id,tk.montant_credit,tk.assistant_id,tk.assistant,tk.date,tk.created_at
    FROM public.tickets tk
    WHERE tk.tenant_id=v_tenant
      AND tk.client_id=p_client_id
      AND tk.statut='VALIDE'
      AND tk.montant_credit>0
    ORDER BY tk.date,tk.created_at,tk.id
    FOR UPDATE
  LOOP
    EXIT WHEN v_restant<=0.01;
    SELECT GREATEST(0,v_ticket.montant_credit-COALESCE(SUM(r.montant),0))
    INTO v_du_ticket
    FROM public.reglements_credit_lignes r
    WHERE r.tenant_id=v_tenant AND r.ticket_id=v_ticket.id;
    IF v_du_ticket>0 THEN
      v_alloc:=LEAST(v_du_ticket,v_restant);
      INSERT INTO public.reglements_credit_lignes(
        paiement_id,ticket_id,montant,assistant_id,assistant,tenant_id
      ) VALUES (
        v_paiement_id,v_ticket.id,v_alloc,v_ticket.assistant_id,v_ticket.assistant,v_tenant
      );
      v_allocations:=v_allocations||jsonb_build_array(jsonb_build_object(
        'ticket_id',v_ticket.id,'montant',v_alloc,'assistant_id',v_ticket.assistant_id,
        'assistant',v_ticket.assistant,'date_vente',v_ticket.date
      ));
      v_restant:=v_restant-v_alloc;
    END IF;
  END LOOP;

  INSERT INTO public.mouvements_caisse(
    type,montant,mode,motif,client_id,assistant,assistant_id,tenant_id,nature,observation,reference_id
  ) VALUES (
    'ENTREE',p_montant,COALESCE(NULLIF(p_mode,''),'ESPECES'),'Règlement crédit',
    p_client_id,v_encaisseur,v_user_id,v_tenant,'REGLEMENT_CREDIT',COALESCE(p_observation,''),'PAY-CREDIT-'||v_paiement_id::text
  );

  RETURN jsonb_build_object(
    'success',true,
    'paiement_id',v_paiement_id,
    'client_id',p_client_id,
    'montant',p_montant,
    'encaisseur_id',v_user_id,
    'encaisseur',v_encaisseur,
    'allocations',v_allocations
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.enregistrer_paiement_credit(bigint,numeric,text,text,text) TO anon, authenticated;

-- Vue RPC simple pour l'audit : dette restante par vente et assistant d'origine.
CREATE OR REPLACE FUNCTION public.get_credit_ledger(p_client_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_tenant uuid:=current_tenant_id(); v_result jsonb;
BEGIN
  IF v_tenant IS NULL THEN RAISE EXCEPTION 'Session invalide'; END IF;
  IF current_user_role() NOT IN ('assistant','admin','Administrateur','caissier','pharmacien','responsable') THEN RAISE EXCEPTION 'Rôle non autorisé'; END IF;
  SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.date_vente,x.ticket_id),'[]'::jsonb) INTO v_result
  FROM (
    SELECT t.id AS ticket_id,t.date AS date_vente,t.client_id,c.nom AS client_nom,
           t.montant_total,t.montant_credit,t.assistant_id,t.assistant,
           COALESCE(SUM(r.montant),0) AS regle,
           GREATEST(0,t.montant_credit-COALESCE(SUM(r.montant),0)) AS reste
    FROM public.tickets t
    JOIN public.clients c ON c.id=t.client_id AND c.tenant_id=v_tenant
    LEFT JOIN public.reglements_credit_lignes r ON r.ticket_id=t.id AND r.tenant_id=v_tenant
    WHERE t.tenant_id=v_tenant AND t.statut='VALIDE' AND t.montant_credit>0
      AND (p_client_id IS NULL OR t.client_id=p_client_id)
    GROUP BY t.id,t.date,t.client_id,c.nom,t.montant_total,t.montant_credit,t.assistant_id,t.assistant
  ) x;
  RETURN v_result;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_credit_ledger(bigint) TO anon, authenticated;

