/*
# PharmaSys - Create all database tables

## Overview
Creates the complete schema for a pharmacy management system with inventory tracking,
sales tickets, stock movements, inventory controls, user management, and pharmacy settings.

## New Tables
1. `inventaire` - Medicine catalog (name, purchase price, sale price, stock, expiry, active status)
2. `historique_ventes` - Sales history log (per-product sale records with profit tracking)
3. `tickets` - Sales tickets (grouped sales with total amounts and profit)
4. `ticket_lignes` - Individual line items within a ticket
5. `mouvements_stock` - Stock movement journal (sales, restocks, cancellations, adjustments)
6. `utilisateurs` - Staff accounts (name, code, role, active status)
7. `controles_inventaire` - Inventory control checks (theoretical vs physical stock)
8. `inventaires` - Inventory cycle sessions (start/end dates, progress tracking)
9. `parametres_pharmacie` - Pharmacy info (name, address, phone, email, logo, slogan)

## Security
- RLS enabled on all tables
- Policies use `TO anon, authenticated` since the app uses a custom login system
  (not Supabase Auth), so the anon-key client needs full CRUD access
- All data is intentionally shared within the single-tenant pharmacy

## Notes
- `inventaire.id` and `utilisateurs.id` use bigint (app generates timestamps as IDs)
- `tickets.id` is text (app generates formatted ticket numbers like TK-20260902-1234)
- `historique_ventes.id` is text (composite: ticketId-productId)
- All tables allow full CRUD for anon+authenticated since the app manages its own auth
*/

-- 1. Inventaire (medicine catalog)
CREATE TABLE IF NOT EXISTS inventaire (
    id bigint PRIMARY KEY,
    nom text NOT NULL DEFAULT '',
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    stock numeric DEFAULT 0,
    peremption date,
    actif boolean DEFAULT true,
    dernier_controle timestamptz,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE inventaire ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_inventaire" ON inventaire;
CREATE POLICY "anon_select_inventaire" ON inventaire FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_inventaire" ON inventaire;
CREATE POLICY "anon_insert_inventaire" ON inventaire FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_inventaire" ON inventaire;
CREATE POLICY "anon_update_inventaire" ON inventaire FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_inventaire" ON inventaire;
CREATE POLICY "anon_delete_inventaire" ON inventaire FOR DELETE TO anon, authenticated USING (true);

-- 2. Utilisateurs (staff accounts)
CREATE TABLE IF NOT EXISTS utilisateurs (
    id bigint PRIMARY KEY,
    nom text NOT NULL DEFAULT '',
    code text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT 'assistant',
    actif boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE utilisateurs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_utilisateurs" ON utilisateurs;
CREATE POLICY "anon_select_utilisateurs" ON utilisateurs FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_utilisateurs" ON utilisateurs;
CREATE POLICY "anon_insert_utilisateurs" ON utilisateurs FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_utilisateurs" ON utilisateurs;
CREATE POLICY "anon_update_utilisateurs" ON utilisateurs FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_utilisateurs" ON utilisateurs;
CREATE POLICY "anon_delete_utilisateurs" ON utilisateurs FOR DELETE TO anon, authenticated USING (true);

-- 3. Tickets (sales tickets)
CREATE TABLE IF NOT EXISTS tickets (
    id text PRIMARY KEY,
    date date NOT NULL,
    heure text DEFAULT '',
    assistant text DEFAULT '',
    assistant_id bigint,
    nb_articles integer DEFAULT 0,
    montant_total numeric DEFAULT 0,
    benefice_total numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    created_at timestamptz DEFAULT now()
);
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_tickets" ON tickets;
CREATE POLICY "anon_select_tickets" ON tickets FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_tickets" ON tickets;
CREATE POLICY "anon_insert_tickets" ON tickets FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_tickets" ON tickets;
CREATE POLICY "anon_update_tickets" ON tickets FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_tickets" ON tickets;
CREATE POLICY "anon_delete_tickets" ON tickets FOR DELETE TO anon, authenticated USING (true);

-- 4. Ticket lignes (line items within a ticket)
CREATE TABLE IF NOT EXISTS ticket_lignes (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticket_id text NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    produit_id bigint,
    nom text DEFAULT '',
    quantite numeric DEFAULT 0,
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    total numeric DEFAULT 0,
    profit numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    created_at timestamptz DEFAULT now()
);
ALTER TABLE ticket_lignes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_ticket_lignes" ON ticket_lignes;
CREATE POLICY "anon_select_ticket_lignes" ON ticket_lignes FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_ticket_lignes" ON ticket_lignes;
CREATE POLICY "anon_insert_ticket_lignes" ON ticket_lignes FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_ticket_lignes" ON ticket_lignes;
CREATE POLICY "anon_update_ticket_lignes" ON ticket_lignes FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_ticket_lignes" ON ticket_lignes;
CREATE POLICY "anon_delete_ticket_lignes" ON ticket_lignes FOR DELETE TO anon, authenticated USING (true);

-- 5. Historique ventes (sales history log)
CREATE TABLE IF NOT EXISTS historique_ventes (
    id text PRIMARY KEY,
    date date NOT NULL,
    heure text DEFAULT '',
    assistant text DEFAULT '',
    assistant_id bigint,
    produit_id bigint,
    nom text DEFAULT '',
    quantite numeric DEFAULT 0,
    pua numeric DEFAULT 0,
    pvu numeric DEFAULT 0,
    total numeric DEFAULT 0,
    profit numeric DEFAULT 0,
    statut text DEFAULT 'VALIDE',
    created_at timestamptz DEFAULT now()
);
ALTER TABLE historique_ventes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_historique_ventes" ON historique_ventes;
CREATE POLICY "anon_select_historique_ventes" ON historique_ventes FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_historique_ventes" ON historique_ventes;
CREATE POLICY "anon_insert_historique_ventes" ON historique_ventes FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_historique_ventes" ON historique_ventes;
CREATE POLICY "anon_update_historique_ventes" ON historique_ventes FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_historique_ventes" ON historique_ventes;
CREATE POLICY "anon_delete_historique_ventes" ON historique_ventes FOR DELETE TO anon, authenticated USING (true);

-- 6. Mouvements stock (stock movement journal)
CREATE TABLE IF NOT EXISTS mouvements_stock (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date text DEFAULT '',
    created_at timestamptz DEFAULT now(),
    assistant text DEFAULT '',
    produit_id bigint,
    produit text DEFAULT '',
    type text DEFAULT '',
    quantite numeric DEFAULT 0,
    stock_avant numeric DEFAULT 0,
    stock_apres numeric DEFAULT 0,
    observation text DEFAULT '',
    ticket text
);
ALTER TABLE mouvements_stock ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_mouvements" ON mouvements_stock;
CREATE POLICY "anon_select_mouvements" ON mouvements_stock FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_mouvements" ON mouvements_stock;
CREATE POLICY "anon_insert_mouvements" ON mouvements_stock FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_mouvements" ON mouvements_stock;
CREATE POLICY "anon_update_mouvements" ON mouvements_stock FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_mouvements" ON mouvements_stock;
CREATE POLICY "anon_delete_mouvements" ON mouvements_stock FOR DELETE TO anon, authenticated USING (true);

-- 7. Inventaires (inventory cycle sessions)
CREATE TABLE IF NOT EXISTS inventaires (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auteur text DEFAULT '',
    date_inventaire timestamptz DEFAULT now(),
    date_cloture timestamptz,
    statut text DEFAULT 'EN_COURS',
    nb_produits_actifs integer DEFAULT 0,
    nb_produits_controles integer DEFAULT 0,
    avancement numeric DEFAULT 0,
    nb_ecarts integer DEFAULT 0,
    pertes numeric DEFAULT 0,
    surplus numeric DEFAULT 0
);
ALTER TABLE inventaires ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_inventaires" ON inventaires;
CREATE POLICY "anon_select_inventaires" ON inventaires FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_inventaires" ON inventaires;
CREATE POLICY "anon_insert_inventaires" ON inventaires FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_inventaires" ON inventaires;
CREATE POLICY "anon_update_inventaires" ON inventaires FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_inventaires" ON inventaires;
CREATE POLICY "anon_delete_inventaires" ON inventaires FOR DELETE TO anon, authenticated USING (true);

-- 8. Controles inventaire (individual inventory checks)
CREATE TABLE IF NOT EXISTS controles_inventaire (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inventaire_id bigint REFERENCES inventaires(id) ON DELETE CASCADE,
    produit_id bigint,
    produit_nom text DEFAULT '',
    stock_systeme numeric DEFAULT 0,
    stock_physique numeric DEFAULT 0,
    ecart numeric DEFAULT 0,
    valeur_ecart numeric DEFAULT 0,
    statut text DEFAULT 'A_ANALYSER',
    cause text,
    observation text,
    stock_corrige boolean DEFAULT false,
    auteur text DEFAULT '',
    date_controle timestamptz DEFAULT now()
);
ALTER TABLE controles_inventaire ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_controles" ON controles_inventaire;
CREATE POLICY "anon_select_controles" ON controles_inventaire FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_controles" ON controles_inventaire;
CREATE POLICY "anon_insert_controles" ON controles_inventaire FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_controles" ON controles_inventaire;
CREATE POLICY "anon_update_controles" ON controles_inventaire FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_controles" ON controles_inventaire;
CREATE POLICY "anon_delete_controles" ON controles_inventaire FOR DELETE TO anon, authenticated USING (true);

-- 9. Parametres pharmacie (pharmacy info settings)
CREATE TABLE IF NOT EXISTS parametres_pharmacie (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom text DEFAULT 'Sekas pharma',
    adresse text DEFAULT '',
    telephone text DEFAULT '',
    email text DEFAULT '',
    rccm text DEFAULT '',
    slogan text DEFAULT '',
    logo_url text DEFAULT ''
);
ALTER TABLE parametres_pharmacie ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_parametres" ON parametres_pharmacie;
CREATE POLICY "anon_select_parametres" ON parametres_pharmacie FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_parametres" ON parametres_pharmacie;
CREATE POLICY "anon_insert_parametres" ON parametres_pharmacie FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_parametres" ON parametres_pharmacie;
CREATE POLICY "anon_update_parametres" ON parametres_pharmacie FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_parametres" ON parametres_pharmacie;
CREATE POLICY "anon_delete_parametres" ON parametres_pharmacie FOR DELETE TO anon, authenticated USING (true);

-- Insert default pharmacy settings
INSERT INTO parametres_pharmacie (id, nom) VALUES (1, 'Sekas pharma')
ON CONFLICT (id) DO NOTHING;

-- Insert default admin user
INSERT INTO utilisateurs (id, nom, code, role, actif) VALUES (99, 'Admin', 'admin', 'admin', true)
ON CONFLICT (id) DO NOTHING;

-- Create indexes for frequently queried columns
CREATE INDEX IF NOT EXISTS idx_inventaire_nom ON inventaire (nom);
CREATE INDEX IF NOT EXISTS idx_inventaire_actif ON inventaire (actif);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_date ON historique_ventes (date);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_produit ON historique_ventes (produit_id);
CREATE INDEX IF NOT EXISTS idx_historique_ventes_assistant ON historique_ventes (assistant);
CREATE INDEX IF NOT EXISTS idx_tickets_date ON tickets (date);
CREATE INDEX IF NOT EXISTS idx_ticket_lignes_ticket ON ticket_lignes (ticket_id);
CREATE INDEX IF NOT EXISTS idx_mouvements_created ON mouvements_stock (created_at);
CREATE INDEX IF NOT EXISTS idx_mouvements_produit ON mouvements_stock (produit_id);
CREATE INDEX IF NOT EXISTS idx_controles_inventaire ON controles_inventaire (inventaire_id);
