-- PharmaSys V9 : Offline queue idempotente + notifications administrateur
CREATE TABLE IF NOT EXISTS public.operations_sync (
  operation_id text PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  operation_type text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'DONE' CHECK (status IN ('DONE')),
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.operations_sync ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operations_sync_select ON public.operations_sync;
CREATE POLICY operations_sync_select ON public.operations_sync FOR SELECT TO anon, authenticated USING (tenant_id=current_tenant_id());
CREATE INDEX IF NOT EXISTS idx_operations_sync_tenant_created ON public.operations_sync(tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  utilisateur_id bigint,
  utilisateur_nom text NOT NULL DEFAULT 'Système',
  type text NOT NULL DEFAULT 'ACTIVITE',
  niveau text NOT NULL DEFAULT 'NORMAL' CHECK (niveau IN ('NORMAL','IMPORTANT','CRITIQUE')),
  titre text NOT NULL,
  message text NOT NULL,
  reference_type text,
  reference_id text,
  lu boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS notifications_select ON public.notifications;
CREATE POLICY notifications_select ON public.notifications FOR SELECT TO anon, authenticated USING (tenant_id=current_tenant_id());
DROP POLICY IF EXISTS notifications_update ON public.notifications;
CREATE POLICY notifications_update ON public.notifications FOR UPDATE TO anon, authenticated USING (tenant_id=current_tenant_id()) WITH CHECK (tenant_id=current_tenant_id());
CREATE INDEX IF NOT EXISTS idx_notifications_tenant_created ON public.notifications(tenant_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.creer_notification_admin(
  p_tenant_id uuid, p_utilisateur_id bigint, p_utilisateur_nom text,
  p_type text, p_niveau text, p_titre text, p_message text,
  p_reference_type text DEFAULT NULL, p_reference_id text DEFAULT NULL
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r text;
BEGIN
  SELECT role INTO r FROM utilisateurs WHERE id=p_utilisateur_id AND tenant_id=p_tenant_id LIMIT 1;
  IF COALESCE(r,'') IN ('admin','Administrateur','responsable','pharmacien') THEN RETURN; END IF;
  INSERT INTO notifications(tenant_id,utilisateur_id,utilisateur_nom,type,niveau,titre,message,reference_type,reference_id)
  VALUES(p_tenant_id,p_utilisateur_id,COALESCE(p_utilisateur_nom,'Système'),p_type,COALESCE(p_niveau,'NORMAL'),p_titre,p_message,p_reference_type,p_reference_id);
END; $$;

CREATE OR REPLACE FUNCTION public.trg_notify_ticket() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  PERFORM creer_notification_admin(NEW.tenant_id,NEW.assistant_id,NEW.assistant,'VENTE','NORMAL','Nouvelle vente',format('Ticket %s · %s Fc · %s',NEW.id,NEW.montant_total,COALESCE(NEW.mode_paiement,'ESPECES')),'ticket',NEW.id);
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notifications_ticket ON public.tickets;
CREATE TRIGGER trg_notifications_ticket AFTER INSERT ON public.tickets FOR EACH ROW EXECUTE FUNCTION trg_notify_ticket();

CREATE OR REPLACE FUNCTION public.trg_notify_mouvement() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE uid bigint; niv text:='NORMAL'; titre text; msg text;
BEGIN
  IF NEW.type='VENTE' THEN RETURN NEW; END IF;
  SELECT id INTO uid FROM utilisateurs WHERE tenant_id=NEW.tenant_id AND nom=NEW.assistant ORDER BY id LIMIT 1;
  IF NEW.type='ANNULATION' THEN niv:='CRITIQUE'; titre:='Annulation / retour stock';
  ELSIF NEW.type='AJUSTEMENT_INVENTAIRE' THEN niv:='IMPORTANT'; titre:='Correction de stock';
  ELSIF NEW.type='REAPPRO' THEN titre:='Réapprovisionnement';
  ELSE titre:='Mouvement de stock'; END IF;
  msg:=format('%s · %s · quantité %s · stock %s → %s',COALESCE(NEW.produit,'Produit'),NEW.type,NEW.quantite,NEW.stock_avant,NEW.stock_apres);
  PERFORM creer_notification_admin(NEW.tenant_id,uid,NEW.assistant,'STOCK',niv,titre,msg,'mouvement_stock',NEW.id::text);
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notifications_mouvement ON public.mouvements_stock;
CREATE TRIGGER trg_notifications_mouvement AFTER INSERT ON public.mouvements_stock FOR EACH ROW EXECUTE FUNCTION trg_notify_mouvement();

CREATE OR REPLACE FUNCTION public.trg_notify_caisse() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE uid bigint;
BEGIN
  SELECT id INTO uid FROM utilisateurs WHERE tenant_id=NEW.tenant_id AND nom=NEW.assistant ORDER BY id LIMIT 1;
  PERFORM creer_notification_admin(NEW.tenant_id,uid,NEW.assistant,'CAISSE',CASE WHEN NEW.type='SORTIE' THEN 'IMPORTANT' ELSE 'NORMAL' END,CASE WHEN NEW.type='SORTIE' THEN 'Sortie de caisse' ELSE 'Entrée de caisse' END,format('%s Fc · %s · %s',NEW.montant,NEW.mode,COALESCE(NEW.motif,'')),'caisse',NEW.id::text);
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notifications_caisse ON public.mouvements_caisse;
CREATE TRIGGER trg_notifications_caisse AFTER INSERT ON public.mouvements_caisse FOR EACH ROW EXECUTE FUNCTION trg_notify_caisse();

CREATE OR REPLACE FUNCTION public.marquer_notifications_lues() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE t uuid:=current_tenant_id(); BEGIN
 IF t IS NULL THEN RAISE EXCEPTION 'Session invalide'; END IF;
 UPDATE notifications SET lu=true WHERE tenant_id=t AND lu=false;
 RETURN jsonb_build_object('success',true);
END; $$;
GRANT EXECUTE ON FUNCTION public.marquer_notifications_lues() TO anon, authenticated;

-- Exécution idempotente des opérations hors-ligne. Le résultat est conservé avec operation_id.
CREATE OR REPLACE FUNCTION public.executer_operation_offline(p_operation_id text,p_operation_type text,p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE t uuid:=current_tenant_id(); r jsonb;
BEGIN
 IF t IS NULL THEN RAISE EXCEPTION 'Session invalide ou expirée'; END IF;
 IF EXISTS(SELECT 1 FROM operations_sync WHERE operation_id=p_operation_id AND tenant_id=t) THEN
   SELECT result INTO r FROM operations_sync WHERE operation_id=p_operation_id AND tenant_id=t;
   RETURN COALESCE(r,jsonb_build_object('success',true,'already_processed',true));
 END IF;
 IF p_operation_id IS NULL OR length(trim(p_operation_id))<8 THEN RAISE EXCEPTION 'Identifiant d''opération invalide'; END IF;

 CASE p_operation_type
 WHEN 'VENTE' THEN
   r:=valider_vente((p_payload->'ticket'->>'id'),(p_payload->'ticket'->>'date')::date,COALESCE(p_payload->'ticket'->>'heure',''),COALESCE(p_payload->'ticket'->>'assistant','Système'),NULLIF(p_payload->'ticket'->>'assistant_id','')::bigint,COALESCE(p_payload->'lignes','[]'::jsonb),COALESCE(p_payload->'ticket'->'paiements','[]'::jsonb));
 WHEN 'REAPPRO' THEN
   r:=reapprovisionner_stock((p_payload->>'p_produit_id')::bigint,(p_payload->>'p_quantite')::numeric,COALESCE(p_payload->>'p_observation','Reapprovisionnement'),COALESCE(p_payload->>'p_assistant','Système'));
 WHEN 'CONTROLE' THEN
   r:=enregistrer_controle_tournant((p_payload->>'p_produit_id')::bigint,(p_payload->>'p_stock_physique')::numeric,p_payload->>'p_cause',COALESCE(p_payload->>'p_observation','Contrôle tournant'),COALESCE(p_payload->>'p_auteur','Système'));
 WHEN 'ANALYSE_CONTROLE' THEN
   r:=traiter_controle_tournant((p_payload->>'p_controle_id')::bigint,p_payload->>'p_cause',COALESCE(p_payload->>'p_observation',''),COALESCE(p_payload->>'p_statut','A_SUIVRE'),COALESCE((p_payload->>'p_corriger_stock')::boolean,false));
 WHEN 'CAISSE' THEN
   r:=enregistrer_mouvement_caisse(p_payload->>'p_type',(p_payload->>'p_montant')::numeric,p_payload->>'p_mode',p_payload->>'p_motif',p_payload->>'p_assistant');
 WHEN 'PAIEMENT_CREDIT' THEN
   r:=enregistrer_paiement_credit((p_payload->>'p_client_id')::bigint,(p_payload->>'p_montant')::numeric,p_payload->>'p_mode',p_payload->>'p_observation',p_payload->>'p_assistant');
 WHEN 'ANNULER_LIGNE_HISTORIQUE' THEN
   r:=annuler_ligne_ticket(p_payload->>'p_historique_id');
 WHEN 'ANNULER_ARTICLE' THEN
   r:=annuler_article_ticket((p_payload->>'p_ligne_id')::bigint);
 WHEN 'ANNULER_TICKET' THEN
   r:=annuler_ticket(p_payload->>'p_ticket_id');
 ELSE RAISE EXCEPTION 'Type d''opération hors-ligne inconnu : %',p_operation_type;
 END CASE;

 INSERT INTO operations_sync(operation_id,tenant_id,operation_type,payload,result) VALUES(p_operation_id,t,p_operation_type,p_payload,r);
 RETURN r;
END; $$;
GRANT EXECUTE ON FUNCTION public.executer_operation_offline(text,text,jsonb) TO anon, authenticated;
