-- PharmaSys V8: Finance, paiements, crédits, caisse et fonctions analytiques.
-- Les opérations financières critiques sont exécutées côté PostgreSQL.

ALTER TABLE public.inventaire ADD COLUMN IF NOT EXISTS categorie text NOT NULL DEFAULT 'Non classé';
ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS mode_paiement text NOT NULL DEFAULT 'ESPECES';
ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS client_id bigint;
ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS montant_paye numeric NOT NULL DEFAULT 0;
ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS montant_credit numeric NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.clients (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nom text NOT NULL,
  telephone text DEFAULT '',
  adresse text DEFAULT '',
  actif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE
);
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_clients_tenant ON public.clients(tenant_id);

CREATE TABLE IF NOT EXISTS public.paiements (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_id text REFERENCES public.tickets(id) ON DELETE SET NULL,
  client_id bigint REFERENCES public.clients(id) ON DELETE SET NULL,
  montant numeric NOT NULL CHECK (montant > 0),
  mode text NOT NULL,
  observation text DEFAULT '',
  assistant text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE
);
ALTER TABLE public.paiements ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_paiements_tenant ON public.paiements(tenant_id);
CREATE INDEX IF NOT EXISTS idx_paiements_ticket ON public.paiements(ticket_id);
CREATE INDEX IF NOT EXISTS idx_paiements_client ON public.paiements(client_id);

CREATE TABLE IF NOT EXISTS public.mouvements_caisse (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type text NOT NULL CHECK (type IN ('ENTREE','SORTIE')),
  montant numeric NOT NULL CHECK (montant > 0),
  mode text NOT NULL DEFAULT 'ESPECES',
  motif text DEFAULT '',
  ticket_id text,
  client_id bigint REFERENCES public.clients(id) ON DELETE SET NULL,
  assistant text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE
);
ALTER TABLE public.mouvements_caisse ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_caisse_tenant_created ON public.mouvements_caisse(tenant_id, created_at DESC);

-- Ajout des nouvelles colonnes si une installation existante utilise déjà tickets.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tickets_client_fk') THEN
    ALTER TABLE public.tickets ADD CONSTRAINT tickets_client_fk FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE SET NULL;
  END IF;
END $$;

-- RLS via tenant courant.
DROP POLICY IF EXISTS clients_select ON public.clients;
DROP POLICY IF EXISTS clients_insert ON public.clients;
DROP POLICY IF EXISTS clients_update ON public.clients;
DROP POLICY IF EXISTS clients_delete ON public.clients;
CREATE POLICY clients_select ON public.clients FOR SELECT TO anon, authenticated USING (tenant_id=current_tenant_id());
CREATE POLICY clients_insert ON public.clients FOR INSERT TO anon, authenticated WITH CHECK (tenant_id=current_tenant_id());
CREATE POLICY clients_update ON public.clients FOR UPDATE TO anon, authenticated USING (tenant_id=current_tenant_id()) WITH CHECK (tenant_id=current_tenant_id());
CREATE POLICY clients_delete ON public.clients FOR DELETE TO anon, authenticated USING (tenant_id=current_tenant_id());

DROP POLICY IF EXISTS paiements_select ON public.paiements;
DROP POLICY IF EXISTS paiements_insert ON public.paiements;
CREATE POLICY paiements_select ON public.paiements FOR SELECT TO anon, authenticated USING (tenant_id=current_tenant_id());
CREATE POLICY paiements_insert ON public.paiements FOR INSERT TO anon, authenticated WITH CHECK (tenant_id=current_tenant_id());
DROP POLICY IF EXISTS caisse_select ON public.mouvements_caisse;
DROP POLICY IF EXISTS caisse_insert ON public.mouvements_caisse;
CREATE POLICY caisse_select ON public.mouvements_caisse FOR SELECT TO anon, authenticated USING (tenant_id=current_tenant_id());
CREATE POLICY caisse_insert ON public.mouvements_caisse FOR INSERT TO anon, authenticated WITH CHECK (tenant_id=current_tenant_id());

-- Vente transactionnelle avec paiements et crédit client.
CREATE OR REPLACE FUNCTION public.valider_vente(
    p_ticket_id text,
    p_date date,
    p_heure text,
    p_assistant text,
    p_assistant_id bigint,
    p_lignes jsonb,
    p_paiements jsonb
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_tenant_id uuid := current_tenant_id();
  l jsonb; pay jsonb;
  pid bigint; q numeric; stock numeric; pua numeric; pvu numeric; nomp text;
  total numeric:=0; profit numeric:=0; nb numeric:=0; paytotal numeric:=0;
  modep text:='ESPECES'; clientid bigint:=NULL; credit numeric:=0;
BEGIN
  IF v_tenant_id IS NULL THEN RAISE EXCEPTION 'Session invalide ou expirée'; END IF;
  IF EXISTS(SELECT 1 FROM tickets WHERE id=p_ticket_id AND tenant_id=v_tenant_id) THEN RAISE EXCEPTION 'Ce ticket existe déjà'; END IF;
  IF p_lignes IS NULL OR jsonb_array_length(p_lignes)=0 THEN RAISE EXCEPTION 'Le panier est vide'; END IF;

  FOR l IN SELECT * FROM jsonb_array_elements(p_lignes) LOOP
    pid := (l->>'produit_id')::bigint; q := (l->>'quantite')::numeric;
    SELECT nom,stock,pua,pvu INTO nomp,stock,pua,pvu FROM inventaire WHERE id=pid AND tenant_id=v_tenant_id AND actif=true FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Produit introuvable : %',pid; END IF;
    IF q IS NULL OR q<=0 OR stock<q THEN RAISE EXCEPTION 'Stock insuffisant pour %',nomp; END IF;
    nb:=nb+q; total:=total+q*coalesce(pvu,0); profit:=profit+q*(coalesce(pvu,0)-coalesce(pua,0));
  END LOOP;

  FOR pay IN SELECT * FROM jsonb_array_elements(COALESCE(p_paiements,'[]'::jsonb)) LOOP
    paytotal:=paytotal+(pay->>'montant')::numeric;
  END LOOP;
  IF jsonb_array_length(COALESCE(p_paiements,'[]'::jsonb))=0 THEN
    paytotal:=total; p_paiements:=jsonb_build_array(jsonb_build_object('mode','ESPECES','montant',total));
  END IF;
  IF abs(paytotal-total)>0.01 THEN RAISE EXCEPTION 'Les paiements (%,) ne correspondent pas au total (%)',paytotal,total; END IF;

  FOR pay IN SELECT * FROM jsonb_array_elements(p_paiements) LOOP
    IF (pay->>'montant')::numeric <= 0 THEN RAISE EXCEPTION 'Montant de paiement invalide'; END IF;
    IF (pay->>'mode')='CREDIT' THEN
      IF clientid IS NULL THEN clientid:=NULLIF(pay->>'client_id','')::bigint; END IF;
      IF NULLIF(pay->>'client_id','')::bigint IS NULL THEN RAISE EXCEPTION 'Un client est obligatoire pour un crédit'; END IF;
      IF NOT EXISTS(SELECT 1 FROM clients WHERE id=(pay->>'client_id')::bigint AND tenant_id=v_tenant_id AND actif=true) THEN RAISE EXCEPTION 'Client crédit introuvable'; END IF;
      IF clientid <> (pay->>'client_id')::bigint THEN RAISE EXCEPTION 'Un seul client peut porter le crédit d’une vente'; END IF;
      credit:=credit+(pay->>'montant')::numeric;
    END IF;
  END LOOP;
  IF jsonb_array_length(p_paiements)>1 THEN modep:='MIXTE'; ELSE modep:=COALESCE(p_paiements->0->>'mode','ESPECES'); END IF;

  INSERT INTO tickets(id,date,heure,assistant,assistant_id,nb_articles,montant_total,benefice_total,statut,mode_paiement,client_id,montant_paye,montant_credit,tenant_id)
  VALUES(p_ticket_id,p_date,p_heure,p_assistant,p_assistant_id,nb,total,profit,'VALIDE',modep,clientid,total-credit,credit,v_tenant_id);

  FOR l IN SELECT * FROM jsonb_array_elements(p_lignes) LOOP
    pid:=(l->>'produit_id')::bigint; q:=(l->>'quantite')::numeric;
    SELECT nom,stock,pua,pvu INTO nomp,stock,pua,pvu FROM inventaire WHERE id=pid AND tenant_id=v_tenant_id FOR UPDATE;
    UPDATE inventaire SET stock=stock-q WHERE id=pid AND tenant_id=v_tenant_id;
    INSERT INTO ticket_lignes(ticket_id,produit_id,nom,quantite,pua,pvu,total,profit,statut,tenant_id) VALUES(p_ticket_id,pid,nomp,q,pua,pvu,q*pvu,q*(pvu-pua),'VALIDE',v_tenant_id);
    INSERT INTO historique_ventes(id,date,heure,assistant,assistant_id,produit_id,nom,quantite,pua,pvu,total,profit,statut,tenant_id) VALUES(p_ticket_id||'-'||pid,p_date,p_heure,p_assistant,p_assistant_id,pid,nomp,q,pua,pvu,q*pvu,q*(pvu-pua),'VALIDE',v_tenant_id);
    INSERT INTO mouvements_stock(date,assistant,produit_id,produit,type,quantite,stock_avant,stock_apres,observation,ticket,tenant_id) VALUES(to_char(now(),'DD/MM/YYYY HH24:MI:SS'),p_assistant,pid,nomp,'VENTE',q,stock,stock-q,'Vente '||p_ticket_id,p_ticket_id,v_tenant_id);
  END LOOP;

  FOR pay IN SELECT * FROM jsonb_array_elements(p_paiements) LOOP
    INSERT INTO paiements(ticket_id,client_id,montant,mode,observation,assistant,tenant_id) VALUES(p_ticket_id,NULLIF(pay->>'client_id','')::bigint,(pay->>'montant')::numeric,COALESCE(pay->>'mode','ESPECES'),'Paiement vente',p_assistant,v_tenant_id);
    IF COALESCE(pay->>'mode','ESPECES') <> 'CREDIT' THEN
      INSERT INTO mouvements_caisse(type,montant,mode,motif,ticket_id,client_id,assistant,tenant_id) VALUES('ENTREE',(pay->>'montant')::numeric,COALESCE(pay->>'mode','ESPECES'),'Vente '||p_ticket_id,p_ticket_id,NULLIF(pay->>'client_id','')::bigint,p_assistant,v_tenant_id);
    END IF;
  END LOOP;

  RETURN jsonb_build_object('success',true,'ticket_id',p_ticket_id,'montant_total',total,'benefice_total',profit,'credit',credit,'mode_paiement',modep);
END; $$;
GRANT EXECUTE ON FUNCTION public.valider_vente(text,date,text,text,bigint,jsonb,jsonb) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.enregistrer_mouvement_caisse(p_type text,p_montant numeric,p_mode text,p_motif text,p_assistant text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE t uuid:=current_tenant_id(); BEGIN
 IF t IS NULL THEN RAISE EXCEPTION 'Session invalide'; END IF;
 IF p_type NOT IN ('ENTREE','SORTIE') OR p_montant<=0 THEN RAISE EXCEPTION 'Mouvement de caisse invalide'; END IF;
 INSERT INTO mouvements_caisse(type,montant,mode,motif,assistant,tenant_id) VALUES(p_type,p_montant,COALESCE(p_mode,'ESPECES'),COALESCE(p_motif,''),COALESCE(p_assistant,'Système'),t);
 RETURN jsonb_build_object('success',true);
END; $$;
GRANT EXECUTE ON FUNCTION public.enregistrer_mouvement_caisse(text,numeric,text,text,text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.enregistrer_paiement_credit(p_client_id bigint,p_montant numeric,p_mode text,p_observation text,p_assistant text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE t uuid:=current_tenant_id(); BEGIN
 IF t IS NULL THEN RAISE EXCEPTION 'Session invalide'; END IF;
 IF p_montant<=0 OR NOT EXISTS(SELECT 1 FROM clients WHERE id=p_client_id AND tenant_id=t AND actif=true) THEN RAISE EXCEPTION 'Client ou montant invalide'; END IF;
 INSERT INTO paiements(client_id,montant,mode,observation,assistant,tenant_id) VALUES(p_client_id,p_montant,COALESCE(p_mode,'ESPECES'),COALESCE(p_observation,'Règlement crédit'),COALESCE(p_assistant,'Système'),t);
 INSERT INTO mouvements_caisse(type,montant,mode,motif,client_id,assistant,tenant_id) VALUES('ENTREE',p_montant,COALESCE(p_mode,'ESPECES'),'Règlement crédit',p_client_id,COALESCE(p_assistant,'Système'),t);
 RETURN jsonb_build_object('success',true);
END; $$;
GRANT EXECUTE ON FUNCTION public.enregistrer_paiement_credit(bigint,numeric,text,text,text) TO anon, authenticated;
