-- PharmaSys V13.2 : seuil d'alerte de stock par catégorie
-- Chaque catégorie d'un tenant possède son propre seuil.

CREATE TABLE IF NOT EXISTS public.seuils_stock_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  categorie text NOT NULL,
  seuil numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seuils_stock_categories_seuil_check CHECK (seuil >= 0),
  CONSTRAINT seuils_stock_categories_categorie_check CHECK (length(trim(categorie)) > 0),
  CONSTRAINT uq_seuils_stock_categories_tenant_categorie UNIQUE (tenant_id, categorie)
);

CREATE INDEX IF NOT EXISTS idx_seuils_stock_categories_tenant
  ON public.seuils_stock_categories(tenant_id);

ALTER TABLE public.seuils_stock_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ssc_select" ON public.seuils_stock_categories;
DROP POLICY IF EXISTS "ssc_insert" ON public.seuils_stock_categories;
DROP POLICY IF EXISTS "ssc_update" ON public.seuils_stock_categories;
DROP POLICY IF EXISTS "ssc_delete" ON public.seuils_stock_categories;

CREATE POLICY "ssc_select" ON public.seuils_stock_categories
  FOR SELECT TO anon, authenticated
  USING (tenant_id = current_tenant_id());

CREATE POLICY "ssc_insert" ON public.seuils_stock_categories
  FOR INSERT TO anon, authenticated
  WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());

CREATE POLICY "ssc_update" ON public.seuils_stock_categories
  FOR UPDATE TO anon, authenticated
  USING (tenant_id = current_tenant_id() AND is_current_admin())
  WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());

CREATE POLICY "ssc_delete" ON public.seuils_stock_categories
  FOR DELETE TO anon, authenticated
  USING (tenant_id = current_tenant_id() AND is_current_admin());

-- Reprend le seuil global historique comme seuil de départ pour les catégories existantes.
-- Cela évite de changer brutalement les alertes lors de la migration.
INSERT INTO public.seuils_stock_categories (tenant_id, categorie, seuil)
SELECT p.tenant_id,
       COALESCE(NULLIF(trim(i.categorie), ''), 'Non classé') AS categorie,
       GREATEST(0, COALESCE(p.seuil_stock_critique, 2)) AS seuil
FROM public.parametres_pharmacie p
JOIN (
  SELECT DISTINCT tenant_id, COALESCE(NULLIF(trim(categorie), ''), 'Non classé') AS categorie
  FROM public.inventaire
  WHERE actif IS DISTINCT FROM false
) i ON i.tenant_id = p.tenant_id
ON CONFLICT (tenant_id, categorie) DO NOTHING;

-- Le seuil global reste conservé pour compatibilité, mais les alertes frontend utilisent désormais cette table.
