-- ============================================================
-- PharmaSys - Traçabilité stricte des crédits et règlements
-- Un règlement est encaissé aujourd'hui mais reste rattaché à la
-- vente/crédit d'origine et donc à l'assistant vendeur d'origine.
-- ============================================================

ALTER TABLE public.paiements
  ADD COLUMN IF NOT EXISTS encaisseur_id bigint,
  ADD COLUMN IF NOT EXISTS encaisseur text;

CREATE INDEX IF NOT EXISTS idx_paiements_credit_client_date
  ON public.paiements(tenant_id, client_id, nature, created_at DESC);

CREATE TABLE IF NOT EXISTS public.reglements_credit_lignes (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  paiement_id bigint NOT NULL REFERENCES public.paiements(id) ON DELETE CASCADE,
  ticket_id text NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  montant numeric NOT NULL CHECK (montant > 0),
  assistant_id bigint,
  assistant text DEFAULT '',
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(paiement_id, ticket_id)
);
ALTER TABLE public.reglements_credit_lignes ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_reglements_credit_ticket
  ON public.reglements_credit_lignes(tenant_id, ticket_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reglements_credit_paiement
  ON public.reglements_credit_lignes(tenant_id, paiement_id);
CREATE INDEX IF NOT EXISTS idx_reglements_credit_assistant
  ON public.reglements_credit_lignes(tenant_id, assistant_id, created_at DESC);

DROP POLICY IF EXISTS reglements_credit_select ON public.reglements_credit_lignes;
CREATE POLICY reglements_credit_select ON public.reglements_credit_lignes
  FOR SELECT TO anon, authenticated
  USING (tenant_id=current_tenant_id() AND is_current_admin());

DROP POLICY IF EXISTS reglements_credit_insert ON public.reglements_credit_lignes;
CREATE POLICY reglements_credit_insert ON public.reglements_credit_lignes
  FOR INSERT TO anon, authenticated
  WITH CHECK (tenant_id=current_tenant_id() AND is_current_admin());

-- Compatibilité : les anciens règlements sans allocation sont répartis
-- chronologiquement sur les anciennes ventes à crédit du même client.
DO $$
DECLARE
  p record;
  t record;
  v_restant numeric;
  v_alloc numeric;
BEGIN
  FOR p IN
    SELECT p.id,p.client_id,p.montant,p.tenant_id,p.created_at
    FROM public.paiements p
    WHERE p.nature='REGLEMENT_CREDIT'
      AND p.client_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.reglements_credit_lignes r WHERE r.paiement_id=p.id)
    ORDER BY p.created_at,p.id
  LOOP
    v_restant:=p.montant;
    FOR t IN
      SELECT tk.id,tk.montant_credit,tk.assistant_id,tk.assistant
      FROM public.tickets tk
      WHERE tk.tenant_id=p.tenant_id
        AND tk.client_id=p.client_id
        AND tk.statut='VALIDE'
        AND tk.montant_credit>0
      ORDER BY tk.date,tk.created_at,tk.id
      FOR UPDATE
    LOOP
      EXIT WHEN v_restant<=0;
      SELECT GREATEST(0,t.montant_credit-COALESCE(SUM(r.montant),0))
      INTO v_alloc
      FROM public.reglements_credit_lignes r
      WHERE r.tenant_id=p.tenant_id AND r.ticket_id=t.id;
      IF v_alloc>0 THEN
        v_alloc:=LEAST(v_alloc,v_restant);
        INSERT INTO public.reglements_credit_lignes(
          paiement_id,ticket_id,montant,assistant_id,assistant,tenant_id
        ) VALUES (
          p.id,t.id,v_alloc,t.assistant_id,t.assistant,p.tenant_id
        ) ON CONFLICT (paiement_id,ticket_id) DO NOTHING;
        v_restant:=v_restant-v_alloc;
      END IF;
    END LOOP;
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.enregistrer_paiement_credit(
  p_client_id bigint,
  p_montant numeric,
  p_mode text DEFAULT 'ESPECES',
  p_observation text DEFAULT '',
  p_assistant text DEFAULT ''
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_tenant uuid:=current_tenant_id();
  v_user_id bigint:=current_user_id();
  v_role text:=current_user_role();
  v_encaisseur text;
  v_paiement_id bigint;
  v_restant numeric:=p_montant;
  v_total_du numeric:=0;
  v_ticket record;
  v_du_ticket numeric;
  v_alloc numeric;
  v_allocations jsonb:='[]'::jsonb;
BEGIN
  IF v_tenant IS NULL OR v_user_id IS NULL THEN RAISE EXCEPTION 'Session invalide'; END IF;
  IF v_role NOT IN ('assistant','admin','Administrateur','caissier','pharmacien','responsable') THEN
    RAISE EXCEPTION 'Rôle non autorisé à encaisser un crédit';
  END IF;
  IF p_montant IS NULL OR p_montant<=0 THEN RAISE EXCEPTION 'Montant invalide'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.clients WHERE id=p_client_id AND tenant_id=v_tenant AND actif=true) THEN
    RAISE EXCEPTION 'Client invalide';
  END IF;

  SELECT nom INTO v_encaisseur
  FROM public.utilisateurs
  WHERE id=v_user_id AND tenant_id=v_tenant AND actif=true;
  IF v_encaisseur IS NULL THEN RAISE EXCEPTION 'Utilisateur actif introuvable'; END IF;

  -- Verrouille les ventes à crédit du client pour empêcher deux encaissements
  -- simultanés de consommer le même solde.
  FOR v_ticket IN
    SELECT tk.id,tk.montant_credit,tk.assistant_id,tk.assistant,tk.date,tk.created_at
    FROM public.tickets tk
    WHERE tk.tenant_id=v_tenant
      AND tk.client_id=p_client_id
      AND tk.statut='VALIDE'
      AND tk.montant_credit>0
    ORDER BY tk.date,tk.created_at,tk.id
    FOR UPDATE
  LOOP
    SELECT GREATEST(0,v_ticket.montant_credit-COALESCE(SUM(r.montant),0))
    INTO v_du_ticket
    FROM public.reglements_credit_lignes r
    WHERE r.tenant_id=v_tenant AND r.ticket_id=v_ticket.id;
    v_total_du:=v_total_du+COALESCE(v_du_ticket,0);
  END LOOP;

  IF p_montant>v_total_du+0.01 THEN
    RAISE EXCEPTION 'Le règlement (%) dépasse la dette restante du client (%)',p_montant,v_total_du;
  END IF;

  INSERT INTO public.paiements(
    ticket_id,client_id,montant,mode,observation,assistant,encaisseur_id,encaisseur,tenant_id,nature
  ) VALUES (
    NULL,p_client_id,p_montant,COALESCE(NULLIF(p_mode,''),'ESPECES'),
    COALESCE(p_observation,'Règlement crédit'),v_encaisseur,v_user_id,v_encaisseur,v_tenant,'REGLEMENT_CREDIT'
  ) RETURNING id INTO v_paiement_id;

  FOR v_ticket IN
    SELECT tk.id,tk.montant_credit,tk.assistant_id,tk.assistant,tk.date,tk.created_at
    FROM public.tickets tk
    WHERE tk.tenant_id=v_tenant
      AND tk.client_id=p_client_id
      AND tk.statut='VALIDE'
      AND tk.montant_credit>0
    ORDER BY tk.date,tk.created_at,tk.id
    FOR UPDATE
  LOOP
    EXIT WHEN v_restant<=0.01;
    SELECT GREATEST(0,v_ticket.montant_credit-COALESCE(SUM(r.montant),0))
    INTO v_du_ticket
    FROM public.reglements_credit_lignes r
    WHERE r.tenant_id=v_tenant AND r.ticket_id=v_ticket.id;
    IF v_du_ticket>0 THEN
      v_alloc:=LEAST(v_du_ticket,v_restant);
      INSERT INTO public.reglements_credit_lignes(
        paiement_id,ticket_id,montant,assistant_id,assistant,tenant_id
      ) VALUES (
        v_paiement_id,v_ticket.id,v_alloc,v_ticket.assistant_id,v_ticket.assistant,v_tenant
      );
      v_allocations:=v_allocations||jsonb_build_array(jsonb_build_object(
        'ticket_id',v_ticket.id,'montant',v_alloc,'assistant_id',v_ticket.assistant_id,
        'assistant',v_ticket.assistant,'date_vente',v_ticket.date
      ));
      v_restant:=v_restant-v_alloc;
    END IF;
  END LOOP;

  INSERT INTO public.mouvements_caisse(
    type,montant,mode,motif,client_id,assistant,assistant_id,tenant_id,nature,observation,reference_id
  ) VALUES (
    'ENTREE',p_montant,COALESCE(NULLIF(p_mode,''),'ESPECES'),'Règlement crédit',
    p_client_id,v_encaisseur,v_user_id,v_tenant,'REGLEMENT_CREDIT',COALESCE(p_observation,''),'PAY-CREDIT-'||v_paiement_id::text
  );

  RETURN jsonb_build_object(
    'success',true,
    'paiement_id',v_paiement_id,
    'client_id',p_client_id,
    'montant',p_montant,
    'encaisseur_id',v_user_id,
    'encaisseur',v_encaisseur,
    'allocations',v_allocations
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.enregistrer_paiement_credit(bigint,numeric,text,text,text) TO anon, authenticated;

-- Vue RPC simple pour l'audit : dette restante par vente et assistant d'origine.
CREATE OR REPLACE FUNCTION public.get_credit_ledger(p_client_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_tenant uuid:=current_tenant_id(); v_result jsonb;
BEGIN
  IF v_tenant IS NULL THEN RAISE EXCEPTION 'Session invalide'; END IF;
  IF current_user_role() NOT IN ('assistant','admin','Administrateur','caissier','pharmacien','responsable') THEN RAISE EXCEPTION 'Rôle non autorisé'; END IF;
  SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.date_vente,x.ticket_id),'[]'::jsonb) INTO v_result
  FROM (
    SELECT t.id AS ticket_id,t.date AS date_vente,t.client_id,c.nom AS client_nom,
           t.montant_total,t.montant_credit,t.assistant_id,t.assistant,
           COALESCE(SUM(r.montant),0) AS regle,
           GREATEST(0,t.montant_credit-COALESCE(SUM(r.montant),0)) AS reste
    FROM public.tickets t
    JOIN public.clients c ON c.id=t.client_id AND c.tenant_id=v_tenant
    LEFT JOIN public.reglements_credit_lignes r ON r.ticket_id=t.id AND r.tenant_id=v_tenant
    WHERE t.tenant_id=v_tenant AND t.statut='VALIDE' AND t.montant_credit>0
      AND (p_client_id IS NULL OR t.client_id=p_client_id)
    GROUP BY t.id,t.date,t.client_id,c.nom,t.montant_total,t.montant_credit,t.assistant_id,t.assistant
  ) x;
  RETURN v_result;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_credit_ledger(bigint) TO anon, authenticated;
