-- PharmaSys V13.4 : catégories centralisées pour Catalogue & Vente
-- Les catégories sont gérées une seule fois par tenant puis réutilisées dans les produits.

CREATE TABLE IF NOT EXISTS public.categories_produits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  nom text NOT NULL,
  actif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT categories_produits_nom_check CHECK (length(trim(nom)) > 0),
  CONSTRAINT uq_categories_produits_tenant_nom UNIQUE (tenant_id, nom)
);

CREATE INDEX IF NOT EXISTS idx_categories_produits_tenant_actif
  ON public.categories_produits(tenant_id, actif, nom);

ALTER TABLE public.categories_produits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categories_produits_select" ON public.categories_produits;
DROP POLICY IF EXISTS "categories_produits_insert" ON public.categories_produits;
DROP POLICY IF EXISTS "categories_produits_update" ON public.categories_produits;
DROP POLICY IF EXISTS "categories_produits_delete" ON public.categories_produits;

CREATE POLICY "categories_produits_select" ON public.categories_produits
  FOR SELECT TO anon, authenticated
  USING (tenant_id = current_tenant_id());

CREATE POLICY "categories_produits_insert" ON public.categories_produits
  FOR INSERT TO anon, authenticated
  WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());

CREATE POLICY "categories_produits_update" ON public.categories_produits
  FOR UPDATE TO anon, authenticated
  USING (tenant_id = current_tenant_id() AND is_current_admin())
  WITH CHECK (tenant_id = current_tenant_id() AND is_current_admin());

CREATE POLICY "categories_produits_delete" ON public.categories_produits
  FOR DELETE TO anon, authenticated
  USING (tenant_id = current_tenant_id() AND is_current_admin());

-- Récupère automatiquement toutes les catégories déjà présentes dans l'inventaire.
INSERT INTO public.categories_produits (tenant_id, nom, actif)
SELECT DISTINCT i.tenant_id, trim(i.categorie), true
FROM public.inventaire i
WHERE i.tenant_id IS NOT NULL
  AND NULLIF(trim(i.categorie), '') IS NOT NULL
  AND lower(trim(i.categorie)) NOT IN ('non classé', 'non classe')
ON CONFLICT (tenant_id, nom) DO UPDATE SET actif = true;
